### ISSUE TITLE
Add pre-requisite section to documentation

### ISSUE THREAD

**Issue by jeffreynolte** [moxienyc/generator-moxie-wp#5]
@desaiuditd - We need to have pre-reqs for this. Joseph spent almost all day getting the tools setup and is still having issues. I feel we should take a step by step approach to documenting how this works including the gulp tasks for some like it neat. This way anyone who can get use out of the tool can easily get up an running.

**Comment by desaiuditd** [comment]
I've responded on Hipchat. Let me know there are still issues in setting up. I've updated the readme with proper steps including gulp tasks for the theme.

https://github.com/moxienyc/generator-moxie-wp

Let me know if anything is still needed.

**Comment by joseph-jalbert** [comment]
@desaiuditd - please just add the bower and the composer pre-reqs.

**Comment by desaiuditd** [comment]
This has been updated. closing it down.
