### ISSUE TITLE
a full setup guidlines doc for some-like-it-neat theme repo

### ISSUE THREAD

**Issue by desaiuditd** [moxienyc/generator-moxie-wp#7]
We need to have a guideline doc with full setup right from accessing the repo to installing pre-requisites to assets generation and deploy process etc.

Following points should make a place in the guidelines doc that should help new developers setup the repo:
- access the repo
- install pre-requisites
  - node
  - npm
  - bower
  - sass ruby gem
  - composer
- assets generation
  - styles
  - js
- coding standards
  - phpcs
  - jshint
- deploy process

/cc @jeffreynolte @mitogh let's add up your suggestions as well in this list, if i've missed anything.

**Comment by desaiuditd** [comment]
A doc template is created with setup guidelines.

https://github.com/moxienyc/generator-moxie-wp/blob/master/app/templates/_readme.md

When we will create a new theme project with generator, this readme file will be copied to the root of the project.

New version of npm package is released. You can update it using following command.

``` bash
npm update -g generator-moxie-wp
```

/cc @jeffreynolte @mitogh Suggestions ?

**Comment by jeffreynolte** [comment]
Nice work @desaiuditd! Looks great to me! I think this will be helpful for us and others  as well.

**Comment by desaiuditd** [comment]
Cool. Closing it out then. Please re-open if something needs to be added. Thanks.
