### ISSUE TITLE
Add task to scaffold out Gravity Form base styles

### ISSUE THREAD

**Issue by jeffreynolte** [moxienyc/generator-moxie-wp#8]
We should have a gist we can import with all of the base styles for Gravity Forms.  This would allow the user to choose yes or no for "will you use gravity forms" and if the answer is yes we insert all the base styles from a sass gist.

cc: @nacho87 @mitogh @desaiuditd

**Comment by mitogh** [comment]
I'm closing this one this is now part of the Lean integration.

https://github.com/moxienyc/Moxie-Lean/issues/8
